/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#44474d",
        "outline": "#75777e",
        "tertiary-container": "#cca830",
        "on-tertiary-fixed": "#241a00",
        "on-secondary-fixed": "#00174b",
        "on-surface": "#131c28",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "primary-container": "#0b1f3a",
        "surface-bright": "#f8f9ff",
        "secondary-fixed": "#dbe1ff",
        "tertiary-fixed-dim": "#e9c349",
        "tertiary": "#735c00",
        "inverse-primary": "#b5c7ea",
        "tertiary-fixed": "#ffe088",
        "surface-container-low": "#eff4ff",
        "surface-tint": "#4d5f7d",
        "outline-variant": "#c4c6ce",
        "inverse-on-surface": "#eaf1ff",
        "on-tertiary-fixed-variant": "#574500",
        "surface": "#f8f9ff",
        "on-tertiary-container": "#4f3e00",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#364764",
        "on-primary-container": "#7587a7",
        "secondary-container": "#6b91fe",
        "surface-variant": "#dae3f4",
        "on-primary-fixed": "#071c36",
        "on-secondary-fixed-variant": "#003ea8",
        "surface-container-highest": "#dae3f4",
        "surface-container-high": "#e0e9f9",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "secondary": "#2c57c1",
        "on-error-container": "#93000a",
        "background": "#f8f9ff",
        "primary-fixed": "#d6e3ff",
        "on-secondary-container": "#002874",
        "error-container": "#ffdad6",
        "inverse-surface": "#28313d",
        "primary": "#000615",
        "primary-fixed-dim": "#b5c7ea",
        "surface-container": "#e5eeff",
        "surface-dim": "#d2daeb",
        "on-background": "#131c28",
        "secondary-fixed-dim": "#b4c5ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "container-max-width": "1280px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        "headline-md": ["Manrope"],
        "headline-xl": ["Manrope"],
        "body-lg": ["Inter"],
        "headline-lg": ["Manrope"],
        "label-md": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Manrope"],
        "display-lg": ["Manrope"],
        "body-sm": ["Inter"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-xl": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg": ["30px", { "lineHeight": "38px", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
